config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :perfils

  resources :usuarios do
    collection do
      get 'localiza'
    end
  end
  

 

  

end

app/models/comprador.rb
class Comprador < ActiveRecord::Base
	has_many :pedidos
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
	belongs_to :comprador
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
	
	has_many :usuarios

end

app/models/usuario.rb
  class Usuario < ActiveRecord::Base
	belongs_to :perfil

	validates_presence_of :name
	
	validates :email,
			  format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,}+\.br)\Z/i, on: :create },
			  uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/perfils_controller.rb
class PerfilsController < ApplicationController
  before_action :set_perfil, only: [:show, :edit, :update, :destroy]

  # GET /perfils
  # GET /perfils.json
  def index
    @perfils = Perfil.all
  end

  # GET /perfils/1
  # GET /perfils/1.json
  def show
  end

  # GET /perfils/new
  def new
    @perfil = Perfil.new
  end

  # GET /perfils/1/edit
  def edit
  end

  # POST /perfils
  # POST /perfils.json
  def create
    @perfil = Perfil.new(perfil_params)

    respond_to do |format|
      if @perfil.save
        format.html { redirect_to @perfil, notice: 'Perfil was successfully created.' }
        format.json { render :show, status: :created, location: @perfil }
      else
        format.html { render :new }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfils/1
  # PATCH/PUT /perfils/1.json
  def update
    respond_to do |format|
      if @perfil.update(perfil_params)
        format.html { redirect_to @perfil, notice: 'Perfil was successfully updated.' }
        format.json { render :show, status: :ok, location: @perfil }
      else
        format.html { render :edit }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfils/1
  # DELETE /perfils/1.json
  def destroy
    @perfil.destroy
    respond_to do |format|
      format.html { redirect_to perfils_url, notice: 'Perfil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfil
      @perfil = Perfil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfil_params
      params.require(:perfil).permit(:tipo)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    
  end

  def localiza
    @usuarios = Usuario.all
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
    @perfils = Perfil.find_all.collect{|p| [p.tipo, p.id]}
    respond_to do |format|
      if @usuario.save        
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
        
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #def localiza
   # @localiza = teste

  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:name, :email, :senha, :perfil_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/find_user_helper.rb
module FindUserHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/localiza_helper.rb
module LocalizaHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/home/index.html.erb
<h4>Escolha sua opção</h4>

<%= link_to "Usuário", new_usuario_path %>
<%= link_to "Perfil", new_perfil_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CadUsuario</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/localiza/index.html.erb
<h1>Localiza Usuários</h1>

<p>Busca</p>
<input><br>
<input type="submit" value="buscar">
<br><br>

app/views/perfils/_form.html.erb
<%= form_for(@perfil) do |f| %>
  <% if @perfil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@perfil.errors.count, "error") %> prohibited this perfil from being saved:</h2>

      <ul>
      <% @perfil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/perfils/edit.html.erb
<h1>Editing perfil</h1>

<%= render 'form' %>

<%= link_to 'Show', @perfil %> |
<%= link_to 'Back', perfils_path %>

app/views/perfils/index.html.erb
<h1>Listing perfils</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perfils.each do |perfil| %>
      <tr>
        <td><%= perfil.tipo %></td>
        <td><%= link_to 'Show', perfil %></td>
        <td><%= link_to 'Edit', edit_perfil_path(perfil) %></td>
        <td><%= link_to 'Destroy', perfil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Perfil', new_perfil_path %>
<%= link_to 'home', root_path %>

app/views/perfils/new.html.erb
<h1>New perfil</h1>

<%= render 'form' %>

<%= link_to 'Back', perfils_path %>

app/views/perfils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @perfil.tipo %>
</p>

<%= link_to 'Edit', edit_perfil_path(@perfil) %> |
<%= link_to 'Back', perfils_path %>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :senha %>
    <%= f.text_field :senha %>
  </div>

  <div class="field">
    <%= f.label :perfil_id %>
    <%= f.select :perfil_id, Perfil.all.collect {|p| [ p.tipo.capitalize, p.id ] }, {include_blank: 'Escolha um perfil'} %>
  </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> 
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Senha</th>
      <th>Perfil</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @usuarios.each do |usuario| %>
      <tr bgcolor="lightgray">
        <td><%= usuario.id %></td>
        <td><%= usuario.name %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.senha %></td>
        <td><%= usuario.perfil_id %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuario', new_usuario_path %><br>
<%= link_to 'Home', root_path %><br>

app/views/usuarios/localiza.html.erb
<h1>Localiza Usuários</h1>

<p>Busca</p>
<input><br><br>
<input type="submit" value="buscar">
<br><br>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @usuario.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @usuario.senha %>
</p>

<p>
  <strong>Perfil:</strong>
  <%= @usuario.perfil_id %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>